#ifndef GEOMETRYSHADEREXAMPLE_GLOBAL_H
#define GEOMETRYSHADEREXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOMETRYSHADEREXAMPLE_LIBRARY)
#define GEOMETRYSHADEREXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define GEOMETRYSHADEREXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOMETRYSHADEREXAMPLE_GLOBAL_H
