#ifndef GEOMETRYSHADEREXAMPLE2_GLOBAL_H
#define GEOMETRYSHADEREXAMPLE2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOMETRYSHADEREXAMPLE2_LIBRARY)
#define GEOMETRYSHADEREXAMPLE2_EXPORT Q_DECL_EXPORT
#else
#define GEOMETRYSHADEREXAMPLE2_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOMETRYSHADEREXAMPLE2_GLOBAL_H
