#ifndef HELLOTRIANGLEEXAMPLE_GLOBAL_H
#define HELLOTRIANGLEEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HELLOTRIANGLEEXAMPLE_LIBRARY)
#define HELLOTRIANGLEEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define HELLOTRIANGLEEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // HELLOTRIANGLEEXAMPLE_GLOBAL_H
