#ifndef TEXTRENDERINGEXAMPLE_GLOBAL_H
#define TEXTRENDERINGEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTRENDERINGEXAMPLE_LIBRARY)
#define TEXTRENDERINGEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define TEXTRENDERINGEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTRENDERINGEXAMPLE_GLOBAL_H
