#ifndef LIGHTCASTERSEXAMPLE_GLOBAL_H
#define LIGHTCASTERSEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIGHTCASTERSEXAMPLE_LIBRARY)
#define LIGHTCASTERSEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define LIGHTCASTERSEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // LIGHTCASTERSEXAMPLE_GLOBAL_H
