#ifndef CREATEOPENGLWINDOWEXAMPLE_GLOBAL_H
#define CREATEOPENGLWINDOWEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CREATEOPENGLWINDOWEXAMPLE_LIBRARY)
#define CREATEOPENGLWINDOWEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define CREATEOPENGLWINDOWEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // CREATEOPENGLWINDOWEXAMPLE_GLOBAL_H
