#ifndef MODELLOADINGEXAMPLE_GLOBAL_H
#define MODELLOADINGEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODELLOADINGEXAMPLE_LIBRARY)
#define MODELLOADINGEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define MODELLOADINGEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // MODELLOADINGEXAMPLE_GLOBAL_H
