#ifndef SHADERSEXAMPLE_GLOBAL_H
#define SHADERSEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHADERSEXAMPLE_LIBRARY)
#define SHADERSEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define SHADERSEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // SHADERSEXAMPLE_GLOBAL_H
