#ifndef COORDINATESYSTEMSEXAMPLE_GLOBAL_H
#define COORDINATESYSTEMSEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COORDINATESYSTEMSEXAMPLE_LIBRARY)
#define COORDINATESYSTEMSEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define COORDINATESYSTEMSEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // COORDINATESYSTEMSEXAMPLE_GLOBAL_H
