#ifndef BASICLIGHTINGEXAMPLE_GLOBAL_H
#define BASICLIGHTINGEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BASICLIGHTINGEXAMPLE_LIBRARY)
#define BASICLIGHTINGEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define BASICLIGHTINGEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // BASICLIGHTINGEXAMPLE_GLOBAL_H
