#ifndef MULTIPLELIGHTSEXAMPLE_GLOBAL_H
#define MULTIPLELIGHTSEXAMPLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTIPLELIGHTSEXAMPLE_LIBRARY)
#define MULTIPLELIGHTSEXAMPLE_EXPORT Q_DECL_EXPORT
#else
#define MULTIPLELIGHTSEXAMPLE_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTIPLELIGHTSEXAMPLE_GLOBAL_H
